---
- name: gather EC2 facts
  hosts: "{{ ec2_hosts }}"
  gather_facts: false 

  vars:
    ec2_region: us-east-1
    ec2_hosts: tag_Name_demo_{{ tower_user_name }}

  tasks:
  - name: gather facts 
    ec2_facts:

- name: terminate hosts
  hosts: "{{ ec2_hosts }}" 
  gather_facts: false
  connection: local  

  vars:
    ec2_hosts: tag_Name_demo_{{ tower_user_name }}

  tasks:
  - name: terminate EC2 hosts
    ec2: >
      region="{{ ec2_region }}"
      instance_ids="{{ item }}"
      state=absent
      wait=True
    with_items: hostvars[inventory_hostname]['ansible_ec2_instance_id'] 

